### ISSUE TITLE
Idea's for addon

### ISSUE THREAD

**Issue by Vanguardsify** [ebisuke/TosAddons#217]
Hello, 

since I saw that you are a person who likes to automate things, I would like to leave some ideas here.
Could I suggest to the "Item Buff Machine" a few extra buttons?
Buttons:
Weapons: Where you would only buff the weapon or Weapons(in case of Trinket), to speed up CM and basic things...Also will be faster, because wont buff all set and we dont need Set buffed in this case bacause Cm's arent that hard in my view
All: Well, this one would look like it is now. And Majoritary people would use for Hard Content(WBR/Moring Hard/Glacia)

Perhaps
Armor: Just buff the armor, but I don't see a useful use for it

Some Ideas
Why Not a Pardorner Auto Buff too ?
Well, I know i can click on 4 Buffs first then after all 4 "Ok's / Cancel" are in middle of my screen i just click spam OK Button

Since u created Awaken and Option Roller, do u think about creating an "Enchant"(yellow add on items, the one that uses Enchant Jewels) Option?

**Comment by ebisuke** [comment]
Hello.
Thank you for your ideas.

I have received mixed feedback on the button to select the equipment to apply the buffs to.
I will consider how to do this, but will implement it in the future.
Enchant armor automation is currently disabled due to a bug that prevented it from properly buffing equipment.
For Pardoner's buffs, you can use the "Shop Helper" to apply the buffs without a dialog. I don't plan to create one for that reason.
I think automating Enchant jewel is a good idea.However, I don't have a lot of enchant jewels, so it would be difficult to test them in action and would take some time to implement.

**Comment by Vanguardsify** [comment]
For "Shop Helper" you mean this one https://github.com/ebisuke/TosAddons/tree/master/shophelpertool, right ?

Is that on manager ? because the only one i can find is NPCShoppingHelperTool version 1.1.0... so if it's the one i linked above i think they are not the same...but on folder it's name is _shophelpertool-📖-v1.1.0 .... well, anyway i tested it...but i think it's not working...since the dialog still showing, maybe a conflict because i play on ITOS(Steam version) ? or maybe some configuration missing from my part.

About closing the issue or not, should i let this open until u created them or i can close it right when u answer me or maybe even when u answer it... I'm asking it because i saw that u open issues for your own addons so you can schedule what u going to do

Ooh, About the Enchant Jewels addon, i think i can help you...i mean i dont know codding, but i have alot of Enchant Jewels, also a friend of mine have over 2k jewels too. If i and my friend could help u someway tell me.

**Comment by ebisuke** [comment]
> For "Shop Helper" you mean this one https://github.com/ebisuke/TosAddons/tree/master/shophelpertool, right ?

No."Shop Helper" is Toukibi's addon.
https://github.com/Toukibi/ToSAddon
My "NPCShoppingHelperTool" is different from "Shop Helper". Originally it was called "ShoppingHelper" but I changed it because there was a possibility of confusion.However, the add-on file name itself has not been changed.

> About closing the issue or not, should i let this open until u created them or i can close it right when u answer me or maybe even when u answer it... I'm asking it because i saw that u open issues for your own addons so you can schedule what u going to do

I had a trick that allowed me to use Issue to paste images into a readme, so I used it.
I didn't think much of it since the issue wasn't made for a while, but I'll close once I've resolved the issue.

> Ooh, About the Enchant Jewels addon, i think i can help you...i mean i dont know codding, but i have alot of Enchant Jewels, also a friend of mine have over 2k jewels too. If i and my friend could help u someway tell me.

Thank you for saying that.I plan to start developing it in due course, so let me consider it again.

**Comment by Vanguardsify** [comment]
Thx for developing my addon idea ^^
