### ISSUE TITLE
ebiremovedialog bug

### ISSUE THREAD

**Issue by Vanguardsify** [ebisuke/TosAddons#220]
Wasn't supposed for EbiRemoveDailog remove those dialogs ?

well the option is checked...

Challenge Mode "Complete": https://youtu.be/3l4ErTGINGM
Singularity Token: https://youtu.be/1CSPQYRUAD0 (same option as above video)
Config: https://pasteboard.co/JwVf6Ff.png

Using TR2 from your blog btw, since here on git u didnt packed them to .ipf

Obs: Yes, I changed map before applying the configs...because other options/funcions are working fine.

Obs²: There will be also other small problem, but this one is not necessary an addon "problem", but a "player"(?) problem...sometimes there are portals that someone drop randomly on the map, so we will have 2 choices here: Everyone change channel or if the party dont want to change channel, i'll need to /erdc unmark Auto Enter into Challenge and then change back where is my party. Or i can also let this Unmarked forever.

Obs³: I'm doing some OW15 Here and the "Challenge Mode Complete" Worked on Stage 5 and didnt on Stage 7... Maybe different Frame/Object when finish on stages other than 7 ?

Thx for your hard work ^^

**Comment by Vanguardsify** [comment]
Ok, I saw u updated it to TR3 on your Blog, so i downloaded it...u Fixed Challenge Mode "Complete", but now Challenge mode enter is broken.

https://youtu.be/QQrXXi23fE0

Ok, After some hours I restarted the Game and now it's asking if i want to Enter or Not in challenge mode... Idk why that happened.

Obs: Before going into Ow15(Above Video), i changed Map... also changed channel and character... so idk why didnt work...

**Comment by ebisuke** [comment]
My email is broken and I'm late in realizing it.Sorry.I'll check it out.

**Comment by Vanguardsify** [comment]
it's all fine...also if u dont understand what i mean't in some area, please tell me...i'll be happy to try to explain it better or even try to record a video with what happen for something stop working the way it should.

**Comment by ebisuke** [comment]
My guess is that it works as expected when you switch the check to ON, but maybe it doesn't go back to the way it was when you switch it to OFF.
The reason is that when you turn it ON, for example, it overwrites the function at the time of entering challenge mode when switching maps or changing characters, but even if you turn it OFF afterwards, the overwritten function will not be restored and the dialog will be in a deleted state.
Therefore, I'm sure that this function will be turned off when you quit the game and restart it.
Anyway, it is a bug and we will consider how to deal with it.
Thank you for the report.
